apiVersion: nais.io/v1alpha1
kind: "Application"
metadata:
  name: aareg-innsyn-arbeidsgiver-api
  namespace: arbeidsforhold
  labels:
    team: arbeidsforhold
spec:
  image: {{{ image }}}
  replicas:
    min: 1
    max: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: labs
  prometheus:
    enabled: true
    path: /arbeidsgiver-arbeidsforhold-api/internal/actuator/prometheus
  liveness:
    path: /arbeidsgiver-arbeidsforhold-api/internal/actuator/health
    initialDelay: 30
  readiness:
    path: /arbeidsgiver-arbeidsforhold-api/internal/actuator/health
    initialDelay: 30
  accessPolicy:
    inbound:
      rules:
        - application: aareg-innsyn-arbeidsgiver
          namespace: arbeidsforhold
    outbound:
      rules:
        - application: demo-arbeidsgiver-fake-login
          namespace: fager
