apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: arbeidsgiver-arbeidsforhold-api
  namespace: default
  labels:
    team: arbeidsgiver
spec:
  image: {{ image }}
  team: arbeidsgiver
  port: 8080
  ingresses:
    - https://arbeidsgiver.nais.preprod.local/arbeidsgiver-arbeidsforhold-api/
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/fss/arbeidsgiver-arbeidsforhold-api/default
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/dev/srvag-arbforhold
  #image: docker.pkg.github.com/navikt/myrepository/myapplication:417dcaa2c839b9da72e0189e2cfdd4e90e9cc6fd
  #       ^--- interpolated from the $IMAGE environment variable in the workflow