apiVersion: nais.io/v1alpha1
kind: "Application"
metadata:
  name: innsyn-aareg-api
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 500m
      memory: 600Mi
  ingresses:
    - https://arbeidsgiver.labs.nais.io/arbeidsgiver-arbeidsforhold-api/
  webproxy: false
  vault:
    enabled: false
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: labs
  prometheus:
    enabled: true
    path: /arbeidsgiver-arbeidsforhold-api/internal/actuator/prometheus
  liveness:
    path: /arbeidsgiver-arbeidsforhold-api/internal/actuator/health
    initialDelay: 30
  readiness:
    path: /arbeidsgiver-arbeidsforhold-api/internal/actuator/health
    initialDelay: 30
  accessPolicy:
    inbound:
      rules:
        - application: innsyn-aareg
          namespace: fager
    outbound:
      rules:
        - application: min-side-ag-fakelogin
