apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: aareg-innsyn-arbeidsgiver-api
  namespace: arbeidsforhold
  labels:
    team: arbeidsforhold
spec:
  image: {{{ image }}}
  ingresses:
    - https://aareg-innsyn-arbeidsgiver-api.prod-fss-pub.nais.io
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: JAVA_OPTS
      value: "-XX:MaxRAMPercentage=75.0"
  envFrom:
    - secret: aareg-innsyn-arbeidsgiver-api
  prometheus:
    enabled: true
    path: /arbeidsgiver-arbeidsforhold-api/internal/actuator/prometheus
  liveness:
    path: /arbeidsgiver-arbeidsforhold-api/internal/actuator/health
    initialDelay: 30
  readiness:
    path: /arbeidsgiver-arbeidsforhold-api/internal/actuator/health
    initialDelay: 30
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvag-arbforhold
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: aareg-innsyn-arbeidsgiver
          namespace: arbeidsforhold
          cluster: prod-gcp
        - application: min-side-arbeidsgiver
          namespace: fager
          cluster: prod-gcp
    outbound:
      rules:
        - application: aareg-services-nais
          namespace: arbeidsforhold
          cluster: prod-fss
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
          cluster: prod-gcp
        - application: pdl-api
          namespace: pdl
          cluster: prod-fss
        - application: kodeverk-api
          namespace: team-rocket
          cluster: prod-fss