apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: innsyn-aareg-api
  namespace: fager
  labels:
    team: fager
spec:
  image: {{ image }}
  team: fager
  port: 8080
  ingresses:
    - https://arbeidsgiver.nais.adeo.no/arbeidsgiver-arbeidsforhold-api/
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  envFrom:
    - configmap: loginservice-idporten
  prometheus:
    enabled: true
    path: /arbeidsgiver-arbeidsforhold-api/internal/actuator/prometheus
  liveness:
    path: /arbeidsgiver-arbeidsforhold-api/internal/actuator/health
    initialDelay: 30
  readiness:
    path: /arbeidsgiver-arbeidsforhold-api/internal/actuator/health
    initialDelay: 30
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/prod/fss/arbeidsgiver-arbeidsforhold-api/default
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvag-arbforhold