name: Test, bygg, deploy
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  bygg:
    name: Bygg
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven

      - run: mvn -B package

      - uses: nais/docker-build-push@v0
        id: gar-push
        with:
          team: arbeidsforhold
          tag: ${{ github.sha }}
          byosbom: target/classes/META-INF/sbom/application.cdx.json

  deploy-dev:
    permissions:
      contents: "read"
      id-token: "write"
    name: Deploy dev
    runs-on: ubuntu-latest
    needs: bygg
    if: github.ref == 'refs/heads/master'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: nais/login@v0
        id: login
        with:
          team: arbeidsforhold
      - name: Deploy til dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          VAR: image=${{ steps.login.outputs.registry }}/arbeidsgiver-innsyn-aareg-api:${{ github.sha }}
          RESOURCE: nais/dev-fss.yaml
          CLUSTER: dev-fss
          REF: ${{ github.sha }}

  deploy-prod:
    permissions:
      contents: "read"
      id-token: "write"
    name: Deploy prod
    runs-on: ubuntu-latest
    needs: deploy-dev
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: nais/login@v0
        id: login
        with:
          team: arbeidsforhold
      - name: Deploy til dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          VAR: image=${{ steps.login.outputs.registry }}/arbeidsgiver-innsyn-aareg-api:${{ github.sha }}
          RESOURCE: nais/dev-fss.yaml
          CLUSTER: dev-fss
          REF: ${{ github.sha }}

      - name: Deploy til prod-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          VAR: image=${{ steps.login.outputs.registry }}/arbeidsgiver-innsyn-aareg-api:${{ github.sha }}
          RESOURCE: nais/prod-fss.yaml
          CLUSTER: prod-fss
          REF: ${{ github.sha }}