name: Deploy til dev (fager)
on:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}:${{ github.sha }}

jobs:
  deploy-branch:
    name: Deploy til dev
    runs-on: ubuntu-latest

    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2

      - name: Deploy
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY_FAGER }}
          CLUSTER: dev-fss
          RESOURCE: nais/dev-fss-fager.yaml
          PRINT_PAYLOAD: true
          REF: ${{ github.sha }}
          IMAGE: ${{ env.IMAGE }}
